# Generated by Django 4.1.1 on 2022-09-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_consulta_horario_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario_consulta',
            field=models.CharField(max_length=30),
        ),
    ]
